#!/usr/bin/env python3
"""
OmniRAG - Enterprise Configuration & Credential Manager
Interactive CLI tool for configuring API keys, enabling/disabling connectors,
and choosing AI providers on Windows & Linux installations.
"""

import os
import sys
import platform
import argparse

# Default config paths based on OS
if platform.system() == "Windows":
    DEFAULT_CONFIG_PATH = os.path.join(os.environ.get("ProgramData", "C:\\ProgramData"), "OmniRAG", "omnirag.env")
else:
    DEFAULT_CONFIG_PATH = "/etc/omnirag/omnirag.env"

# Fallback local path
LOCAL_CONFIG_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.env"))


def load_env_file(filepath: str) -> dict:
    config = {}
    if os.path.exists(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    k, v = line.split("=", 1)
                    config[k.strip()] = v.strip().strip("\"'")
    return config


def save_env_file(filepath: str, config: dict):
    os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# OmniRAG Enterprise Dynamic RAG Configuration\n")
        f.write(f"# Auto-generated by omnirag-config on {platform.system()}\n\n")
        
        for k, v in sorted(config.items()):
            f.write(f'{k}="{v}"\n')
    print(f"\n[SUCCESS] Configuration saved to: {filepath}")


def prompt_user(prompt_text: str, default_val: str = "") -> str:
    if default_val:
        res = input(f"{prompt_text} [{default_val}]: ").strip()
        return res if res else default_val
    return input(f"{prompt_text}: ").strip()


def run_interactive_wizard(config_path: str):
    print("=" * 70)
    print("          OmniRAG Dynamic Enterprise RAG - Configuration Setup")
    print("=" * 70)
    print("Configure your AI model providers, vector databases, and cloud connectors.\n")

    current_config = load_env_file(config_path) if os.path.exists(config_path) else load_env_file(LOCAL_CONFIG_PATH)

    # 1. Embedding Provider
    print("--- [1] EMBEDDING ENGINE ---")
    print("Options:")
    print("  1. fastembed   (Recommended: $0 cost, runs locally via ONNX)")
    print("  2. openrouter  (Cloud embeddings via OpenRouter API)")
    print("  3. openai      (OpenAI text-embedding-3-small)")
    emb_choice = prompt_user("Choose Embedding Provider (1/2/3)", "1")
    emb_map = {"1": "fastembed", "2": "openrouter", "3": "openai"}
    current_config["EMBEDDING_PROVIDER"] = emb_map.get(emb_choice, emb_choice)

    # 2. LLM Provider
    print("\n--- [2] LLM GENERATION PROVIDER ---")
    print("Options:")
    print("  1. groq        (Ultra-fast free/low-cost inference)")
    print("  2. openrouter  (Multi-model access: Claude, GPT-4, Llama 3)")
    print("  3. openai      (OpenAI GPT-4o / GPT-4o-mini)")
    print("  4. mock        (Offline local demonstration)")
    llm_choice = prompt_user("Choose LLM Provider (1/2/3/4)", "1")
    llm_map = {"1": "groq", "2": "openrouter", "3": "openai", "4": "mock"}
    current_config["LLM_PROVIDER"] = llm_map.get(llm_choice, llm_choice)

    # 3. Vector Database
    print("\n--- [3] VECTOR DATABASE ---")
    print("Options:")
    print("  1. pinecone    (Pinecone Serverless Vector Store)")
    print("  2. mock        (In-memory local vector store)")
    vec_choice = prompt_user("Choose Vector Store (1/2)", "1")
    current_config["VECTOR_STORE_PROVIDER"] = "pinecone" if vec_choice == "1" else "mock"

    # 4. Credentials & API Keys
    print("\n--- [4] CREDENTIALS & API KEYS (Press Enter to keep existing/skip) ---")
    if current_config["VECTOR_STORE_PROVIDER"] == "pinecone":
        current_config["PINECONE_API_KEY"] = prompt_user("Pinecone API Key", current_config.get("PINECONE_API_KEY", ""))
        current_config["PINECONE_INDEX_NAME"] = prompt_user("Pinecone Index Name", current_config.get("PINECONE_INDEX_NAME", "omnirag-index"))

    if current_config["LLM_PROVIDER"] == "groq":
        current_config["GROQ_API_KEY"] = prompt_user("Groq API Key", current_config.get("GROQ_API_KEY", ""))
    elif current_config["LLM_PROVIDER"] == "openrouter" or current_config["EMBEDDING_PROVIDER"] == "openrouter":
        current_config["OPENROUTER_API_KEY"] = prompt_user("OpenRouter API Key", current_config.get("OPENROUTER_API_KEY", ""))
    elif current_config["LLM_PROVIDER"] == "openai" or current_config["EMBEDDING_PROVIDER"] == "openai":
        current_config["OPENAI_API_KEY"] = prompt_user("OpenAI API Key", current_config.get("OPENAI_API_KEY", ""))

    # 5. Connectors Enable/Disable
    print("\n--- [5] CLOUD STORAGE CONNECTORS ---")
    current_config["ENABLE_S3_CONNECTOR"] = prompt_user("Enable AWS S3 Connector? (true/false)", current_config.get("ENABLE_S3_CONNECTOR", "true"))
    current_config["ENABLE_AZURE_CONNECTOR"] = prompt_user("Enable Azure Blob Connector? (true/false)", current_config.get("ENABLE_AZURE_CONNECTOR", "true"))
    current_config["ENABLE_SUPABASE_CONNECTOR"] = prompt_user("Enable Supabase Storage Connector? (true/false)", current_config.get("ENABLE_SUPABASE_CONNECTOR", "true"))
    current_config["ENABLE_CONFLUENCE_CONNECTOR"] = prompt_user("Enable Confluence Wiki Connector? (true/false)", current_config.get("ENABLE_CONFLUENCE_CONNECTOR", "true"))

    # Ports
    current_config["PYTHON_RAG_PORT"] = prompt_user("Python RAG Port", current_config.get("PYTHON_RAG_PORT", "8000"))
    current_config["GO_ENGINE_PORT"] = prompt_user("Go Engine Port", current_config.get("GO_ENGINE_PORT", "8080"))

    # Save
    save_env_file(config_path, current_config)
    # Also sync local .env if in dev directory
    if os.path.exists(os.path.dirname(LOCAL_CONFIG_PATH)):
        save_env_file(LOCAL_CONFIG_PATH, current_config)


def main():
    parser = argparse.ArgumentParser(description="OmniRAG Configuration & Credentials Tool")
    parser.add_argument("--config", "-c", default=DEFAULT_CONFIG_PATH if os.path.exists(os.path.dirname(DEFAULT_CONFIG_PATH)) else LOCAL_CONFIG_PATH, help="Path to config file")
    parser.add_argument("--set", nargs=2, metavar=("KEY", "VALUE"), help="Set a specific configuration key without wizard")
    parser.add_argument("--get", metavar="KEY", help="Get a configuration key value")
    parser.add_argument("--list", action="store_true", help="List current configuration")
    args = parser.parse_args()

    config_file = args.config

    if args.set:
        k, v = args.set
        cfg = load_env_file(config_file)
        cfg[k] = v
        save_env_file(config_file, cfg)
        print(f"Set {k}={v}")
        return

    if args.get:
        cfg = load_env_file(config_file)
        val = cfg.get(args.get, "")
        print(val)
        return

    if args.list:
        cfg = load_env_file(config_file)
        print(f"\nConfiguration at {config_file}:")
        for k, v in sorted(cfg.items()):
            # Mask secret keys
            if any(s in k.lower() for s in ["key", "secret", "token", "password"]):
                masked = v[:4] + "••••••••" if len(v) > 6 else "••••••••"
                print(f"  {k} = {masked}")
            else:
                print(f"  {k} = {v}")
        return

    # Default interactive wizard
    run_interactive_wizard(config_file)


if __name__ == "__main__":
    main()
